#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    laravel-pacs-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^laravel-pacs\.ddev\.site$`)
      
      service: "laravel-pacs-xhgui-80"
      tls: false
      # middlewares:
      #   - "laravel-pacs-redirectHttps"
    laravel-pacs-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^laravel-pacs\.ddev\.site$`)
      
      service: "laravel-pacs-web-80"
      tls: false
      # middlewares:
      #   - "laravel-pacs-redirectHttps"
    laravel-pacs-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^laravel-pacs\.ddev\.site$`)
      
      service: "laravel-pacs-web-8025"
      tls: false
      # middlewares:
      #   - "laravel-pacs-redirectHttps"
    
    
    laravel-pacs-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^laravel-pacs\.ddev\.site$`)
      
      service: "laravel-pacs-xhgui-80"
      
      tls: true
      
    
    
    laravel-pacs-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^laravel-pacs\.ddev\.site$`)
      
      service: "laravel-pacs-web-80"
      
      tls: true
      
    laravel-pacs-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^laravel-pacs\.ddev\.site$`)
      
      service: "laravel-pacs-web-8025"
      
      tls: true
      
    

  middlewares:
    laravel-pacs-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    laravel-pacs-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-laravel-pacs-xhgui:80
        
    
    laravel-pacs-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-laravel-pacs-web:80
        
    laravel-pacs-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-laravel-pacs-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/laravel-pacs.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/laravel-pacs.key